---
title: "hw3_yg2625"
author: "Yue Gu"
date: "October 13, 2018"
output: github_document
---


```{r setup, include=FALSE}
library(tidyverse)
library(p8105.datasets)

knitr::opts_chunk$set(echo = TRUE,
                      fig.width = 15,
                      fig.height = 5,
                      fig.asp = 0.6,
                      out.width = "90%")

```



# Problem 1
## Data Cleaning
```{r}
data(brfss_smart2010)
brfss_data = 
  brfss_smart2010 %>% 
  janitor::clean_names() %>% 
  rename(.data = ., state = locationabbr, county = locationdesc) %>% 
  filter(.data = ., topic == "Overall Health", response == "Excellent" || response == "Very good" || response == "Good" || response == "Fair" || reponse == "Poor") %>% 
  mutate(.data = ., response = as.factor(response)) %>% 
  arrange(.data = .,  match(response,c("Excellent", "Very good", "Good", "Fair", "Poor")))

```

## Answering questions
```{r}
brfss_data %>% 
  filter(year == 2002) %>% 
  group_by(state) %>% 
  summarize(n_obs = n_distinct(county) == 7) %>% 
  filter(n_obs == T)

brfss_data %>% 
  group_by(year, state) %>% 
  summarize(n_obs = n_distinct(county)) %>%
  ggplot(aes(x = year, y = n_obs, color = state)) + geom_line()

brfss_data %>% 
  filter(.data = ., response == "Excellent", state == "NY", year == "2002"|year == "2006"|year == "2010") %>%
  group_by(year, state) %>% 
  summarize(mean_data = mean(data_value)，
            sd_data = sd(data_value)) %>% 
  knitr::kable(digits = 2)

brfss_data %>% 
  group_by(year, state, response) %>% 
  summarize(mean_data = mean(data_value)) %>% 
  ggplot(aes(x = year, y = mean_data, color = state)) + 
    geom_line() + 
    facet_grid(.~response)
```

# Problem 2

## Description of exploration
```{r}
data("instacart")
insta_data =
  instacart
  

dim(insta_data)
n_distinct(insta_data$order_id)
n_distinct(insta_data$product_id)
n_distinct(insta_data$user_id)
n_distinct(insta_data$aisle_id)
n_distinct(insta_data$department_id)
```

## Aisles
```{r}
n_distinct(insta_data$aisle)
head(arrange(count(insta_data, aisle_id), desc(n)), n = 1)

## Plot
insta_data %>% 
  group_by(aisle_id) %>% 
  summarize(n = n()) %>% 
  ggplot(aes(x = as.character(aisle_id), y = n, color = as.character(aisle_id))) +
    geom_point(alpha = 0.5) +
    viridis::scale_color_viridis(
    name = "Aisle ID", 
    discrete = TRUE
  ) + 
    theme(legend.position = "bottom")

## Table for most pop items
insta_data %>% 
  filter(.data = ., aisle == "baking ingredients" | aisle == "dog food care" | aisle == "packaged vegetables fruits") %>% 
  group_by(aisle, product_name) %>%
  summarize(n = n()) %>% 
  filter(min_rank(desc(n)) == 1) %>% 
  knitr::kable()

## Table for hr of the day
insta_data %>% 
  filter(.data = ., product_name == "Pink Lady Apples" | product_name == "Coffee Ice Cream") %>% 
  group_by(order_dow, product_name) %>% 
  summarize(mean_hr = mean(order_hour_of_day)) %>% 
  spread(key = order_dow, value = mean_hr) %>%
  rename(Mon = "0", Tues = "1", Wed = "2", Thrs = "3", Fri = "4", Sat = "5", Sun = "6", Product = product_name) %>% 
  knitr::kable(digit = 2)
```






